module Fix44.CompoundItemDU

open Fix44.CompoundItems



type FIXGroup =
    | Advertisement_NoUnderlyingsGrp of Advertisement_NoUnderlyingsGrp
    | AllocationInstructionAck_NoAllocsGrp of AllocationInstructionAck_NoAllocsGrp
    | AllocationInstruction_NoAllocsGrp of AllocationInstruction_NoAllocsGrp
    | AllocationInstruction_NoExecsGrp of AllocationInstruction_NoExecsGrp
    | AllocationReportAck_NoAllocsGrp of AllocationReportAck_NoAllocsGrp
    | AllocationReport_NoAllocsGrp of AllocationReport_NoAllocsGrp
    | AllocationReport_NoExecsGrp of AllocationReport_NoExecsGrp
    | BidResponse_NoBidComponentsGrp of BidResponse_NoBidComponentsGrp
    | CollateralAssignment_NoUnderlyingsGrp of CollateralAssignment_NoUnderlyingsGrp
    | CollateralRequest_NoUnderlyingsGrp of CollateralRequest_NoUnderlyingsGrp
    | CollateralResponse_NoUnderlyingsGrp of CollateralResponse_NoUnderlyingsGrp
    | CrossOrderCancelReplaceRequest_NoSidesGrp of CrossOrderCancelReplaceRequest_NoSidesGrp
    | CrossOrderCancelRequest_NoSidesGrp of CrossOrderCancelRequest_NoSidesGrp
    | DerivativeSecurityList_NoRelatedSymGrp of DerivativeSecurityList_NoRelatedSymGrp
    | ExecutionReport_NoLegsGrp of ExecutionReport_NoLegsGrp
    | IndicationOfInterest_NoLegsGrp of IndicationOfInterest_NoLegsGrp
    | LinesOfTextGrp of LinesOfTextGrp
    | ListStatus_NoOrdersGrp of ListStatus_NoOrdersGrp
    | ListStrikePrice_NoUnderlyingsGrp of ListStrikePrice_NoUnderlyingsGrp
    | MarketDataIncrementalRefresh_NoMDEntriesGrp of MarketDataIncrementalRefresh_NoMDEntriesGrp
    | MarketDataRequest_NoRelatedSymGrp of MarketDataRequest_NoRelatedSymGrp
    | MassQuoteAcknowledgement_NoQuoteEntriesGrp of MassQuoteAcknowledgement_NoQuoteEntriesGrp
    | MassQuoteAcknowledgement_NoQuoteSetsGrp of MassQuoteAcknowledgement_NoQuoteSetsGrp
    | MassQuote_NoQuoteEntriesGrp of MassQuote_NoQuoteEntriesGrp
    | MultilegOrderCancelReplaceRequest_NoAllocsGrp of MultilegOrderCancelReplaceRequest_NoAllocsGrp
    | MultilegOrderCancelReplaceRequest_NoLegsGrp of MultilegOrderCancelReplaceRequest_NoLegsGrp
    | NetworkStatusResponse_NoCompIDsGrp of NetworkStatusResponse_NoCompIDsGrp
    | NewOrderList_NoOrdersGrp of NewOrderList_NoOrdersGrp
    | NewOrderMultileg_NoAllocsGrp of NewOrderMultileg_NoAllocsGrp
    | NewOrderMultileg_NoLegsGrp of NewOrderMultileg_NoLegsGrp
    | NoAffectedOrdersGrp of NoAffectedOrdersGrp
    | NoAllocsGrp of NoAllocsGrp
    | NoAltMDSourceGrp of NoAltMDSourceGrp
    | NoBidComponentsGrp of NoBidComponentsGrp
    | NoBidDescriptorsGrp of NoBidDescriptorsGrp
    | NoCapacitiesGrp of NoCapacitiesGrp
    | NoClearingInstructionsGrp of NoClearingInstructionsGrp
    | NoCollInquiryQualifierGrp of NoCollInquiryQualifierGrp
    | NoCompIDsGrp of NoCompIDsGrp
    | NoContAmtsGrp of NoContAmtsGrp
    | NoContraBrokersGrp of NoContraBrokersGrp
    | NoDatesGrp of NoDatesGrp
    | NoDistribInstsGrp of NoDistribInstsGrp
    | NoDlvyInstGrp of NoDlvyInstGrp
    | NoEventsGrp of NoEventsGrp
    | NoExecsGrp of NoExecsGrp
    | NoHopsGrp of NoHopsGrp
    | NoIOIQualifiersGrp of NoIOIQualifiersGrp
    | NoInstrAttribGrp of NoInstrAttribGrp
    | NoLegAllocsGrp of NoLegAllocsGrp
    | NoLegSecurityAltIDGrp of NoLegSecurityAltIDGrp
    | NoLegStipulationsGrp of NoLegStipulationsGrp
    | NoLegsGrp of NoLegsGrp
    | NoMDEntriesGrp of NoMDEntriesGrp
    | NoMDEntryTypesGrp of NoMDEntryTypesGrp
    | NoMiscFeesGrp of NoMiscFeesGrp
    | NoMsgTypesGrp of NoMsgTypesGrp
    | NoNested2PartyIDsGrp of NoNested2PartyIDsGrp
    | NoNested2PartySubIDsGrp of NoNested2PartySubIDsGrp
    | NoNested3PartyIDsGrp of NoNested3PartyIDsGrp
    | NoNested3PartySubIDsGrp of NoNested3PartySubIDsGrp
    | NoNestedPartyIDsGrp of NoNestedPartyIDsGrp
    | NoNestedPartySubIDsGrp of NoNestedPartySubIDsGrp
    | NoOrdersGrp of NoOrdersGrp
    | NoPartyIDsGrp of NoPartyIDsGrp
    | NoPartySubIDsGrp of NoPartySubIDsGrp
    | NoPosAmtGrp of NoPosAmtGrp
    | NoPositionsGrp of NoPositionsGrp
    | NoQuoteEntriesGrp of NoQuoteEntriesGrp
    | NoQuoteQualifiersGrp of NoQuoteQualifiersGrp
    | NoQuoteSetsGrp of NoQuoteSetsGrp
    | NoRegistDtlsGrp of NoRegistDtlsGrp
    | NoRelatedSymGrp of NoRelatedSymGrp
    | NoRoutingIDsGrp of NoRoutingIDsGrp
    | NoSecurityAltIDGrp of NoSecurityAltIDGrp
    | NoSecurityTypesGrp of NoSecurityTypesGrp
    | NoSettlInstGrp of NoSettlInstGrp
    | NoSettlPartyIDsGrp of NoSettlPartyIDsGrp
    | NoSettlPartySubIDsGrp of NoSettlPartySubIDsGrp
    | NoSidesGrp of NoSidesGrp
    | NoStipulationsGrp of NoStipulationsGrp
    | NoStrikesGrp of NoStrikesGrp
    | NoTradesGrp of NoTradesGrp
    | NoTradingSessionsGrp of NoTradingSessionsGrp
    | NoTrdRegTimestampsGrp of NoTrdRegTimestampsGrp
    | NoUnderlyingSecurityAltIDGrp of NoUnderlyingSecurityAltIDGrp
    | NoUnderlyingStipsGrp of NoUnderlyingStipsGrp
    | NoUnderlyingsGrp of NoUnderlyingsGrp
    | PositionReport_NoUnderlyingsGrp of PositionReport_NoUnderlyingsGrp
    | QuoteRequestReject_NoLegsGrp of QuoteRequestReject_NoLegsGrp
    | QuoteRequestReject_NoRelatedSymGrp of QuoteRequestReject_NoRelatedSymGrp
    | QuoteRequest_NoLegsGrp of QuoteRequest_NoLegsGrp
    | QuoteRequest_NoRelatedSymGrp of QuoteRequest_NoRelatedSymGrp
    | QuoteResponse_NoLegsGrp of QuoteResponse_NoLegsGrp
    | QuoteStatusReport_NoLegsGrp of QuoteStatusReport_NoLegsGrp
    | Quote_NoLegsGrp of Quote_NoLegsGrp
    | RFQRequest_NoRelatedSymGrp of RFQRequest_NoRelatedSymGrp
    | SecurityList_NoLegsGrp of SecurityList_NoLegsGrp
    | SecurityList_NoRelatedSymGrp of SecurityList_NoRelatedSymGrp
    | TradeCaptureReportAck_NoAllocsGrp of TradeCaptureReportAck_NoAllocsGrp
    | TradeCaptureReportAck_NoLegsGrp of TradeCaptureReportAck_NoLegsGrp
    | TradeCaptureReport_NoLegsGrp of TradeCaptureReport_NoLegsGrp
    | TradeCaptureReport_NoSidesGrp of TradeCaptureReport_NoSidesGrp



