(*
 * Copyright (C) 2016-2017 Ian Spratt <ian144@hotmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *)
 
module HeaderTrailerGenerator

open System.Xml.Linq
open System.IO

open FIXGenTypes


let ReadHeader (excludeFieldNames:Set<string>) (xl:XElement) : Header =
    let items = FIXSpecReader.ReadItems ["Header"] xl |> List.filter (FIXItem.excludeFieldsFilter excludeFieldNames)
    {HItems = items}



let ReadTrailer (excludeFieldNames:Set<string>) (xl:XElement)  =
    let items = FIXSpecReader.ReadItems ["Trailer"] xl |> List.filter (FIXItem.excludeFieldsFilter excludeFieldNames)
    {TItems = items}



let genHeader (sw:StreamWriter) (hdr:Header) (trailer:Trailer) : unit =
    // generate the group write functions
    sw.WriteLine "module Fix44.HeaderTrailer"
    sw.WriteLine ""
    sw.WriteLine "// **** this file is generated by fsFixGen ****"
    sw.WriteLine ""
    sw.WriteLine "open OneOrTwo"
    sw.WriteLine "open Fix44.Fields"
    sw.WriteLine "open Fix44.CompoundItems"

    sw.WriteLine ""
    sw.WriteLine "type Header = {"
    hdr.HItems |> (CommonGenerator.writeFIXItemList sw)
    sw.WriteLine  "    }"
    sw.WriteLine ""

    sw.WriteLine ""
    sw.WriteLine "type Trailer = {"
    trailer.TItems |> (CommonGenerator.writeFIXItemList sw)
    sw.WriteLine  "    }"
    sw.WriteLine ""


